apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
spec:
  template:
    spec:
      containers:
      - name: kube-hunter
        image: booyaabes/kube-hunter 
        command: ["python", "kube-hunter.py"]
        args: ["--pod"]
      imagePullPolicy: always
      restartPolicy: Never
  backoffLimit: 4

